# Generated by Django 4.1.2 on 2022-10-15 18:54

from django.db import migrations, models
import trasher.models


class Migration(migrations.Migration):

    dependencies = [
        ('trasher', '0004_alter_user_creation_date_alter_user_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=trasher.models.PathAndRename('./static/images')),
        ),
    ]
